export const mockTopics = [
    { topicId: "1", topic: "Future dreams" },
    { topicId: "2", topic: "Memorable trips" },
    { topicId: "3", topic: "Kindness" },
    { topicId: "4", topic: "Climate change" },
    { topicId: "5", topic: "Homework" },
    { topicId: "6", topic: "Feeling proud" },
    { topicId: "7", topic: "Seasons" },
    { topicId: "8", topic: "Mistakes" },
    { topicId: "9", topic: "Future self" },
    { topicId: "10", topic: "Imagination" },
    { topicId: "11", topic: "Technology" },
    { topicId: "12", topic: "Heroes" },
    { topicId: "13", topic: "Friendship" },
    { topicId: "14", topic: "Happiness" },
    { topicId: "15", topic: "Pollution" },
    { topicId: "16", topic: "Good days" },
    { topicId: "17", topic: "Reading" },
    { topicId: "18", topic: "Superpowers" },
    { topicId: "19", topic: "School" },
    { topicId: "20", topic: "Teamwork" },
    { topicId: "21", topic: "Graduation" },
    { topicId: "22", topic: "Decisions" },
    { topicId: "23", topic: "Books" },
    { topicId: "24", topic: "Beauty" },
    { topicId: "25", topic: "Helping" },
    { topicId: "26", topic: "Food" },
    { topicId: "27", topic: "Hobbies" },
    { topicId: "28", topic: "Animals" },
    { topicId: "29", topic: "Holidays" },
    { topicId: "30", topic: "Inventions" },
    { topicId: "31", topic: "Skills" },
    { topicId: "32", topic: "Honesty" },
    { topicId: "33", topic: "Traditions" },
    { topicId: "34", topic: "Nature" },
    { topicId: "35", topic: "Gifts" },
    { topicId: "36", topic: "Emotions" },
    { topicId: "37", topic: "Vacations" },
    { topicId: "38", topic: "Music" },
    { topicId: "39", topic: "Learning" },
    { topicId: "40", topic: "New starts" },
    { topicId: "41", topic: "Weekends" },
    { topicId: "42", topic: "Countries" },
    { topicId: "43", topic: "Community" },
    { topicId: "44", topic: "Zoos" },
    { topicId: "45", topic: "Leadership" },
    { topicId: "46", topic: "Transportation" },
    { topicId: "47", topic: "Jobs" },
    { topicId: "48", topic: "Sports" },
    { topicId: "49", topic: "Movies" },
    { topicId: "50", topic: "Society" }
  ];
  