export const mockGenres = [
    { genreId: "1", skills: "register", genre: "cause-effect", description: "Explores the reasons behind an event and its consequences." },
    { genreId: "2", skills: "register", genre: "narrative", description: "Tells a story with characters, a plot, and a setting." },
    { genreId: "3", skills: "register", genre: "problem-solution", description: "Identifies a problem and proposes one or more solutions." },
    { genreId: "4", skills: "register", genre: "compare-contrast", description: "Examines the similarities and differences between two or more subjects." },
    { genreId: "5", skills: "register", genre: "description", description: "Provides detailed information about a person, place, thing, or event." },
    { genreId: "6", skills: "register", genre: "procedure", description: "Explains how to do something step by step." },
    { genreId: "7", skills: "register", genre: "summary", description: "Condenses a larger piece of writing into its main points." },
    { genreId: "8", skills: "research", genre: "research paper introduction", description: "Introduces the topic, background, and purpose of a research paper." },
    { genreId: "9", skills: "research", genre: "research paper method section", description: "Describes the methods and procedures used in a research study." },
    { genreId: "10", skills: "research", genre: "research paper results section", description: "Presents the findings of a research study." },
    { genreId: "11", skills: "research", genre: "research paper discussion section", description: "Interprets the results and discusses their implications." },
    { genreId: "12", skills: "research", genre: "research paper conclusion section", description: "Summarizes the main findings and suggests future research directions." },
    { genreId: "13", skills: "research", genre: "literature review", description: "Reviews existing research on a specific topic." },
    { genreId: "14", skills: "essay", genre: "argumentative essay", description: "Presents a clear argument supported by evidence." },
    { genreId: "15", skills: "essay", genre: "persuasive essay", description: "Aims to convince the reader of a particular viewpoint." },
    { genreId: "16", skills: "essay", genre: "expository essay", description: "Explains a topic in a straightforward manner." },
    { genreId: "17", skills: "essay", genre: "analytical essay", description: "Analyzes a piece of literature, art, or a concept." },
    { genreId: "18", skills: "essay", genre: "reflective essay", description: "Reflects on personal experiences and insights." },
    { genreId: "19", skills: "essay", genre: "critical essay", description: "Critically evaluates a piece of literature, art, or a concept." },
    { genreId: "20", skills: "essay", genre: "biographical essay", description: "Tells the life story of a person." },
    { genreId: "21", skills: "essay", genre: "autobiographical essay", description: "Tells the author's own life story." },
    { genreId: "22", skills: "reporting", genre: "travel writing", description: "Describes experiences and observations from traveling." },
    { genreId: "23", skills: "reporting", genre: "journalistic writing", description: "Reports on current events and issues in a factual manner." },
    { genreId: "24", skills: "reporting", genre: "opinion piece", description: "Expresses the author's personal opinion on a topic."}
]